title: Adhityan B
logo: photo.jpeg
theme: jekyll-theme-minimal
show_downloads: true
theme: jekyll-theme-minimal

description: >-
  Data Analyst | Power BI | Excel | SQL | Tableau |
  Helping businesses make data-driven decisions with clear, compelling dashboards.
